### ISSUE TITLE
Scanastudio script manager duplicates some protocols in  4.0.15

### ISSUE THREAD

**Issue by YoannD42** [ikalogic/ScanaStudio-scripts-v3#14]
In its last version, 4.0.15, running on a Windows 10 (1909 Enterprise) 64bits machine, scanastudio script manager will duplicate some protocols : 

- 1-Wire is displayed 3 times. 
- SPI Flash memory is displayed 2 times. 

Issue persists after clicking refresh, or a ScanaStudio restart. I can't reproduce the issue under linux (debian 64 bits).

![1-Wire](https://user-images.githubusercontent.com/68429111/87788032-e98ac480-c83c-11ea-9ce8-70708561f1c0.png)
![SPI Flash](https://user-images.githubusercontent.com/68429111/87788031-e8f22e00-c83c-11ea-84ca-6db05ff2c109.png)

**Comment by YoannD42** [comment]
In addition, I just sent the application and session logs, with a link to this Issue, if it can help to reproduce. 

Thank you !

**Comment by BastitNi** [comment]
Hi @YoannD42,
With the log file you just sent, it appears that the duplicated script were made "manually". Their names are *protocolname_copy0.js*

Thus, you should remove them manually, because ScanaStudio must not delete a script written by a user.

**Comment by YoannD42** [comment]
Hi, thank you for the fast answer, 

For the _copy0 I agree, that's my copies, that's the 2 scripts you see in the screenshots, named "SPI GTX DAC" (this one is a copy from spi) and "STIM DECODER" (this one is copied from pwm). 

For the rest, 1-Wire and Spi Flash protocols, it looks like... different ? The 2 copies were made at the same timedate, and not names _copyx,  could it be after an update ? 

![image](https://user-images.githubusercontent.com/68429111/87790284-9e72b080-c840-11ea-96e3-d012fb152b5f.png)

**Comment by BastitNi** [comment]
Thank you for your feedback. I'll investigate around that.
Unfortunately, ScanaStudio won't be able to remove these script as I said before, but it should prevent their creation.
It will probably be fixed in the next release.

**Comment by YoannD42** [comment]
Perfect, Thanks for taking feedback.
