### ISSUE TITLE
CRC computing with CAN

### ISSUE THREAD

**Issue by RaphaKPS** [ikalogic/ScanaStudio-scripts-v3#20]
Hello,
I discover that the CRC computing with CAN Bus protocol is dedicated to CAN-FD, thus generating an error when using standard CAN frames (something dealing with code line 1856 probably...).
Thanks.

**Comment by ikalogic** [comment]
Thanks for letting me know.

I think my mistake was to think that CAN-FD CRC was compatible with non FD CAN system. Which aparently is not the case. 

I'll have to modify the code to have different computing depending on the mode.

Thanks,
